### ISSUE TITLE
Cannot build with current SDK (4.5)

### ISSUE THREAD

**Issue by MoTLD** [ygalanter/BLUE_SUN_QUOTES#1]
I tried to build this watchface, but `pebble build` returned the error "An invalid value of '2' was found in the 'sdkVersion' field of the project's package.json. The latest supported value for this field is '3'."

My understanding is that `pebble convert-project` is supposed to update older projects that use appinfo.json instead of package.json, but it returns the same error.

What I was hoping to do was strip out the quotes and "no bt" indicator to create a light version with no distractions, but if I can't even get it to compile unmodified I'm stuck.

**Comment by ygalanter** [comment]
Wow, haven't looked at this project in a while. But I *think* if I remember correctly, I was able to compile it in CloudPebble under latest SDK. Let me take a look at what's going on.

**Comment by ygalanter** [comment]
Ok, I just pushed the update, get the latest, you should be able to build it.

**Comment by MoTLD** [comment]
Thanks for the quick response! I tried to build the new version using the command line SDK (I've never used CloudPebble because I only got my watch last year and the servers were supposed to be going down, and still are in a few months, so I wanted to be able to do everything locally) but it's still failing. At least it's attempting to build now, but it gives me a warning and quite a few errors. Perhaps there's some library I need? I have a default install of the SDK with nothing added or changed and I am able to build other projects.

I was going to attach a text file with the full listing of the output I'm getting but for some reason github won't let me so here it is cut and pasted, sorry for the length:

motld@monstrosity:~/pebble-dev/BLUE_SUN_QUOTES$ pebble build
Setting top to                           : /home/motld/pebble-dev/BLUE_SUN_QUOTES 
Setting out to                           : /home/motld/pebble-dev/BLUE_SUN_QUOTES/build 
Checking for program webpack             : /home/motld/.pebble-sdk/SDKs/current/node_modules/.bin/webpack 
WARNING: enableMultiJS is not enabled for this project. message_keys.json will not be included in your project unless you add it to your pebble-js-app.js file. 
Found Pebble SDK for emery in:           : /home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/emery 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for diorite in:         : /home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/diorite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for chalk in:           : /home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/chalk 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for basalt in:          : /home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/basalt 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for aplite in:          : /home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/aplite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
'configure' finished successfully (0.271s)
Waf: Entering directory `/home/motld/pebble-dev/BLUE_SUN_QUOTES/build'
Waf: Leaving directory `/home/motld/pebble-dev/BLUE_SUN_QUOTES/build'
Traceback (most recent call last):
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Scripting.py", line 146, in run_command
    ctx.execute()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Scripting.py", line 351, in execute
    return execute_method(self)
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Build.py", line 106, in execute
    self.execute_build()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Build.py", line 115, in execute_build
    self.compile()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Build.py", line 180, in compile
    self.producer.start()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Runner.py", line 149, in start
    self.refill_task_list()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Runner.py", line 98, in refill_task_list
    self.outstanding.extend(self.biter.next())
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Build.py", line 410, in get_build_iterator
    self.post_group()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Build.py", line 394, in post_group
    f()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/TaskGen.py", line 109, in post
    v()
  File "/home/motld/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/extras/report_memory_usage.py", line 39, in generate_memory_usage_report
    max_resources=task_gen.env.PLATFORM["MAX_RESOURCES_SIZE"]
TypeError: list indices must be integers, not str
Build failed.

**Comment by ygalanter** [comment]
It looks like those errors come from Python code of SDK itself. Maybe something is misconfigured there? But do try CloudPebble (you can import project there directly from GitHub). Btw, I believe CloudPebble will continue to run by community even after servers shut down. You can also install a local instance of CloudPebble. And about that error "TypeError: list indices must be integers, not str"- I am not very familiar with Python, but from what I see it quite common. perhaps there's a fix.

**Comment by MoTLD** [comment]
I'll try it in CloudPebble. Thanks for your help!

**Comment by 30m3e** [comment]
Hello! @MoTLD I was looking for the solution that I have got the same errors same as yours. But we are on different project. I found one solution on stackoverflow which is fixed it by replacing new wscript (sdkversion 4.5) with old one and need to add two line: 

1) "sdkVersion": "3",
2) "enableMultiJS": true, 

in appinfo.json. but unfortunately, missing app entry point error has emerged and still looking for the solution.

**Comment by PanicMan** [comment]
Have the same Problem here, has anyone found an solution?

**Comment by phcreery** [comment]
Same issue here.

```
File "/home/rebble/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/extras/report_memory_usage.py", line 39, in generate_memory_usage_report
    max_resources=task_gen.env.PLATFORM["MAX_RESOURCES_SIZE"]
TypeError: list indices must be integers, not str
Build failed.
```

Any luck finding a solution?

**Comment by MoTLD** [comment]
Sorry, I moved on to something else not long after the original conversation and never did try it out on cloudpebble or do any further troubleshooting on the SDK. My "solution" was to use watchface-generator.de to create a simple static Blue Sun watchface, which you should find in the rebble app store if you search for blue sun, firefly, or motld.

Now that I'm thinking about it again I might revisit this issue and see if I can make any more progress, if so I'll report back.

**Comment by ygalanter** [comment]
Hi guys, sorry this repo has been abandoned for a while, but since Pebble itself is resurrected, so was this project. It was also completely redesigned, brought to modern SDK and all modern platforms, while retaining the core functionality.
